import {createRequire} from 'node:module';
import {once} from 'node:events';
import {readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {gzipSync} from 'node:zlib';
import {chromium,expect} from '@playwright/test';
import publicRouter from '../artifacts/api-server/src/routes/public-site';
const require=createRequire(new URL('../artifacts/api-server/package.json',import.meta.url));
const express=require('express'),cookieParser=require('cookie-parser');
process.env.CATALOG_MODE='demo';
const app=express();app.use(cookieParser());
app.use((req:any,res:any,next:any)=>{const send=res.send.bind(res);res.send=(body:any)=>{if(typeof body==='string'&&req.headers['accept-encoding']?.includes('gzip')){res.set('Content-Encoding','gzip');res.set('Vary','Accept-Encoding');return send(gzipSync(body))}return send(body)};next()});
app.use('/api',async(req:any,res:any)=>{if(req.method!=='GET')return res.sendStatus(405);const r=await fetch('http://127.0.0.1:5313/api'+req.url,{headers:{cookie:req.headers.cookie||''}});res.status(r.status);for(const key of ['content-type','cache-control','server-timing'])if(r.headers.get(key))res.set(key,r.headers.get(key));res.send(await r.text())});
app.use('/assets',async(req:any,res:any,next:any)=>{try{const path=resolve('artifacts/marketplace/dist/assets','.'+req.path);if(!path.startsWith(resolve('artifacts/marketplace/dist/assets')+'\\'))return res.sendStatus(400);const body=await readFile(path);res.type(path);if(/\.(js|css)$/.test(path)&&req.headers['accept-encoding']?.includes('gzip')){res.set('Content-Encoding','gzip');res.send(gzipSync(body))}else res.send(body)}catch{next()}});
app.use('/catalog-art',express.static(resolve('artifacts/marketplace/public/catalog-art'),{immutable:true,maxAge:'1y'}));app.use(express.static(resolve('artifacts/marketplace/dist'),{index:false}));app.use(async(req:any,res:any,next:any)=>{if(process.env.PERF_SQL!=='true'||!/^\/(?:$|search$|product\/|store\/|games\/|sets\/)/.test(req.path))return next();const r=await fetch('http://127.0.0.1:5313'+req.originalUrl,{headers:{cookie:req.headers.cookie||''},redirect:'manual'});if(r.status>=300&&r.status<400){res.status(r.status).set('Location',r.headers.get('location')||'/').end();return;}res.status(r.status);res.type(r.headers.get('content-type')||'text/html');res.send(await r.text());});app.use(publicRouter);app.use((_req:any,res:any)=>res.sendFile(resolve('artifacts/marketplace/dist/index.html')));
const server=app.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();if(!address||typeof address==='string')throw Error('address');const base='http://127.0.0.1:'+address.port;process.env.PUBLIC_SITE_URL=base;
const browser=await chromium.launch({channel:'chrome'});const routes:any[]=[],measurements:any[]=[];
try{
 for(const profile of (process.env.PERF_PROFILE ? [process.env.PERF_PROFILE] : ['desktop','mobile-4g'])){
  const context=await browser.newContext({viewport:profile==='desktop'?{width:1440,height:950}:{width:390,height:844},deviceScaleFactor:profile==='desktop'?1:2,isMobile:profile!=='desktop',hasTouch:profile!=='desktop'});const page=await context.newPage();const hydrationErrors:string[]=[];page.on('pageerror',e=>hydrationErrors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/hydrat|Minified React error|server rendered/i.test(m.text()))hydrationErrors.push(m.text())});const cdp=await context.newCDPSession(page);if(profile!=='desktop'){await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:80,downloadThroughput:200000,uploadThroughput:93750});await cdp.send('Emulation.setCPUThrottlingRate',{rate:4})}
  await page.addInitScript(()=>{(window as any).__lcp=0;new PerformanceObserver(list=>{const e:any=list.getEntries().at(-1); (window as any).__lcp=e?.startTime; (window as any).__lcpDetail={url:e?.url,loadTime:e?.loadTime,element:e?.element?.outerHTML?.slice(0,350)}}).observe({type:'largest-contentful-paint',buffered:true})});
  const start=performance.now();await page.goto(base+'/search?lang=en&sort=name&limit=12');await page.locator('#catalog-browse-form').waitFor();await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>document.querySelector('[aria-busy]')?.getAttribute('aria-busy')==='false');
  const readyMs=Math.round(performance.now()-start);await page.waitForFunction(()=>Array.from(document.querySelectorAll('[data-catalog-artwork] img')).filter(i=>i.getBoundingClientRect().top<innerHeight&&i.getBoundingClientRect().bottom>0).every(i=>(i as HTMLImageElement).complete&&(i as HTMLImageElement).naturalWidth>0));await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));const artworkReadyMs=Math.round(performance.now()-start);const metrics=await page.evaluate(()=>{const nav=performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;const scripts=performance.getEntriesByType('resource').filter((r:any)=>/\.js(?:\?|$)/.test(r.name)) as PerformanceResourceTiming[];return {lcpDetail:(window as any).__lcpDetail,ttfbMs:Math.round(nav.responseStart),observedLcpMs:Math.round((window as any).__lcp),artworkTransferBytes:(performance.getEntriesByType("resource") as PerformanceResourceTiming[]).filter(r=>r.name.includes("/catalog-art/")).reduce((n,r)=>n+r.transferSize,0),scriptRequests:scripts.length,scriptTransferBytes:scripts.reduce((n,r)=>n+r.transferSize,0),resources:(performance.getEntriesByType('resource') as PerformanceResourceTiming[]).map(r=>({url:r.name,start:Math.round(r.startTime),ms:Math.round(r.duration),bytes:r.transferSize})).sort((a,b)=>b.ms-a.ms).slice(0,20),catalogHydrationFetches:performance.getEntriesByType('resource').filter(r=>r.name.includes('/api/catalog/page')).length}});
  await page.screenshot({path:'docs/evidence/performance/catalog-'+profile+'.png'});
  const filters=[],filterArtworkMs=[];for(const q of ['Pikachu','Charizard','Pikachu']){await page.locator('#catalog-browse-query').fill(q);const response=page.waitForResponse(r=>r.url().includes('/api/catalog/page')&&new URL(r.url()).searchParams.get('q')===q);const t=performance.now();await page.locator('.troc-browse-search button').click();await response;await expect(page.locator('[aria-busy]').first()).toHaveAttribute('aria-busy','false');filters.push(Math.round(performance.now()-t));await page.waitForFunction(()=>Array.from(document.querySelectorAll('[data-catalog-artwork] img')).filter(i=>i.getBoundingClientRect().top<innerHeight&&i.getBoundingClientRect().bottom>0).every(i=>(i as HTMLImageElement).complete&&(i as HTMLImageElement).naturalWidth>0));await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));filterArtworkMs.push(Math.round(performance.now()-t))}expect(hydrationErrors).toEqual([]);measurements.push({profile,devicePixelRatio:profile==='desktop'?1:2,readyMs,artworkReadyMs,...metrics,filterMs:filters,filterArtworkMs,hydrationErrors});await context.close();
 }
 if(process.env.PERF_ROUTES !== 'skip') for(const [role,paths] of Object.entries({guest:['/','/search','/sign-in','/sign-up','/help','/roadmap','/about','/sell','/developers','/docs','/collection','/smart-cart','/cart'],buyer:['/account','/account/orders','/account/messages','/account/settings'],seller:['/seller/dashboard','/seller/inventory','/seller/orders','/seller/messages','/seller/analytics','/seller/settings','/seller/storefront','/seller/team','/seller/promotions','/seller/payouts'],admin:['/admin/waitlist','/admin/reports']})){
  const c=await browser.newContext();if(role!=='guest')await c.request.post('http://127.0.0.1:4313/api/dev/session',{headers:{Origin:'http://127.0.0.1:4313'},data:{role}});const p=await c.newPage();let errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));for(const path of paths){errors=[];const t=performance.now();await p.goto(base+path+'?lang=en');await p.waitForFunction(()=>{const h=document.querySelector('main h1');return h?.textContent&&!/Opening your workspace|Loading/i.test(h.textContent)});routes.push({role,path,readyMs:Math.round(performance.now()-t),title:await p.locator('main h1').first().innerText(),errors:[...errors]});expect(errors).toEqual([])}await c.close();
 }
 const hydrationMatrix=[];
 const catalog=await(await fetch('http://127.0.0.1:5313/api/catalog/page?path=/search&lang=en')).json();
 for(const lang of ['en','fr'])for(const theme of ['dark','light']){
  const c=await browser.newContext();await c.addCookies([{name:'troc_theme',value:theme,url:base}]);const p=await c.newPage();const errors:string[]=[];
  p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/hydrat|Minified React error|server rendered/i.test(m.text()))errors.push(m.text())});
  for(const path of ['/','/search','/product/'+catalog.results[0].product.slug,'/store/cartes-du-nord']){await p.goto(base+path+'?lang='+lang);await expect(p.locator('[aria-busy]').first()).toHaveAttribute('aria-busy','false');await expect(p.locator('html')).toHaveAttribute('lang',lang+'-CA');expect(errors).toEqual([]);hydrationMatrix.push({path,lang,theme,errors:0})}await c.close();
 }
 await writeFile('docs/evidence/performance/hydration-matrix.json',JSON.stringify(hydrationMatrix,null,2));
 const html=await (await fetch(base+'/search?lang=fr&game=pokemon')).text();expect(html).toContain('window.__TROC_PAGE__');expect(html).toContain('rel="canonical"');expect(html).toContain('hreflang="fr-CA"');expect(html).toContain('noindex,follow');expect(html).toContain('catalog-browse-form');
 await writeFile('docs/evidence/performance/'+(process.env.PERF_LABEL||'production-check')+'.json',JSON.stringify({environment:process.env.PERF_SQL==='true'?'built assets/SSR; local SQL-backed retained real records; embedded PostgreSQL, not hosted load evidence':'local built assets+SSR with gzip; API uses local demo; not CDN/hosted load evidence',measurements,routes,seo:{serverRenderedSearch:true,canonical:true,hreflang:true,facetsRemainNoindex:true}},null,2));console.log(JSON.stringify({measurements,routes:routes.length,routeErrors:routes.filter(r=>r.errors.length)},null,2));
}finally{await browser.close();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()))}
