export const copy = {
  adminSignIn: [
    "Sign in to review prelaunch leads.",
    "Connectez-vous pour examiner les inscriptions.",
  ],
  adminForbidden: [
    "Your account does not have administrator access.",
    "Votre compte ne dispose pas d’un accès administrateur.",
  ],
  adminConflict: [
    "This lead changed. Reload the latest data before reviewing and saving again. Your change was not saved.",
    "Cette inscription a changé. Rechargez les données actuelles avant de les examiner et d’enregistrer à nouveau. Votre modification n’a pas été enregistrée.",
  ],
  adminUnavailable: [
    "The service is temporarily unavailable. Reload the data and try again.",
    "Le service est temporairement indisponible. Rechargez les données et réessayez.",
  ],
  reload: ["Reload latest data", "Recharger les données actuelles"],
  listConcerned: ["Which interest list?", "Liste concernée"],
  withdrawalHelp: [
    "Use the private code shown after your original signup. This page does not send email or recover lost codes.",
    "Utilisez le code privé affiché après votre inscription initiale. Cette page n’envoie pas de courriel et ne récupère pas les codes perdus.",
  ],
  contactSection: ["Contact details", "Coordonnées"],
  activitySection: [
    "Your collecting or selling",
    "Votre activité de collection ou de vente",
  ],
  consentSection: ["Your choices", "Vos choix"],
  requiredNote: [
    "Fields are required unless marked optional.",
    "Les champs sont obligatoires sauf indication contraire.",
  ],
  optionalLabel: ["optional", "facultatif"],
  development: [
    "In development · Canadian early access",
    "En développement · Accès anticipé au Canada",
  ],
  title: [
    "Your next chapter in collecting.",
    "Le prochain chapitre de votre collection.",
  ],
  intro: [
    "Help shape a Canadian card marketplace. Choose your path and hear about launch opportunities when they are ready.",
    "Participez à la création d’une place de marché canadienne de cartes. Choisissez votre parcours pour recevoir les nouvelles du lancement.",
  ],
  collector: ["Collector Early Access", "Accès anticipé collectionneur"],
  seller: ["Founding Seller interest", "Intérêt vendeur fondateur"],
  collectorText: [
    "Find the cards you want, from Canadian sellers. Join the collector list.",
    "Trouvez les cartes recherchées auprès de vendeurs canadiens. Rejoignez la liste des collectionneurs.",
  ],
  sellerText: [
    "Tell us about your inventory and how you sell today. This is an interest list, not seller approval.",
    "Parlez-nous de votre inventaire et de vos ventes actuelles. Cette liste d’intérêt ne constitue pas une approbation vendeur.",
  ],
  promise: [
    "No launch date, invitation, integration, badge or financial reward is guaranteed. Marketplace pricing will be in CAD.",
    "Aucune date, invitation, intégration, distinction ou récompense financière n’est garantie. Les prix seront en dollars canadiens.",
  ],
  email: ["Email address", "Adresse courriel"],
  province: ["Province or territory", "Province ou territoire"],
  games: ["Games you collect or sell", "Jeux collectionnés ou vendus"],
  channels: ["Where you buy or sell", "Où achetez-vous ou vendez-vous ?"],
  optional: ["Optional collector details", "Détails facultatifs de collection"],
  frequency: ["Buying frequency", "Fréquence d’achat"],
  frustrations: [
    "What could be easier? (optional)",
    "Que pourrait-on améliorer ? (facultatif)",
  ],
  wishlist: [
    "Cards you are looking for (optional)",
    "Cartes recherchées (facultatif)",
  ],
  contact: ["Contact or store name", "Nom du contact ou de la boutique"],
  software: ["Inventory tools", "Outils d’inventaire"],
  inventory: [
    "Approximate inventory size",
    "Taille approximative de l’inventaire",
  ],
  sellerType: ["Seller type", "Type de vendeur"],
  experience: ["Selling experience", "Expérience de vente"],
  adult: ["I am 18 or older.", "J’ai 18 ans ou plus."],
  country: ["I am based in Canada.", "Je réside au Canada."],
  consent: [
    "I agree to receive TROC prelaunch updates and invitations by email. I can withdraw at any time using my saved withdrawal code.",
    "J’accepte de recevoir les nouvelles et invitations de prélancement TROC par courriel. Je peux me désinscrire à tout moment avec mon code conservé.",
  ],
  analytics: [
    "Allow optional measurement of my visit and form progress.",
    "Autoriser la mesure facultative de ma visite et de ma progression dans le formulaire.",
  ],
  privacy: [
    "We use your email and answers to organize early access and contact you about TROC. Leads are private to authorized administrators. Optional analytics records steps, not field contents. Save your withdrawal code; no email is sent automatically.",
    "Votre courriel et vos réponses servent à organiser l’accès anticipé et à vous contacter au sujet de TROC. Seuls les administrateurs autorisés peuvent consulter ces données. Les statistiques facultatives enregistrent les étapes, pas le contenu des champs. Conservez votre code de désinscription; aucun courriel n’est envoyé automatiquement.",
  ],
  submit: ["Join the interest list", "Rejoindre la liste d’intérêt"],
  busy: ["Saving…", "Enregistrement…"],
  success: [
    "Request received. Existing entries stay unchanged. Save this private withdrawal code: it works only if this request created an entry. Keep the original code if you joined before.",
    "Demande reçue. Les inscriptions existantes restent inchangées. Conservez ce code privé : il fonctionne uniquement si cette demande a créé une inscription. Si vous êtes déjà inscrit, gardez votre code initial.",
  ],
  error: [
    "We could not save this request. Check your fields and try again. If early access is unavailable, please return later.",
    "Impossible d’enregistrer cette demande. Vérifiez les champs et réessayez. Si l’accès anticipé est indisponible, revenez plus tard.",
  ],
  withdraw: ["Withdraw consent", "Retirer mon consentement"],
  withdrawal: ["Private withdrawal code", "Code privé de désinscription"],
  withdrawn: [
    "Request processed. If the code matched, updates are now stopped.",
    "Demande traitée. Si le code correspondait, les envois sont maintenant désactivés.",
  ],
  back: ["Early access home", "Accueil accès anticipé"],
  choose: ["Choose an option", "Choisissez une option"],
  admin: ["Private prelaunch leads", "Contacts de prélancement privés"],
  load: ["Apply filters", "Appliquer les filtres"],
  save: ["Save review", "Enregistrer le suivi"],
  next: ["Next page", "Page suivante"],
  previous: ["Previous page", "Page précédente"],
  empty: ["No matching leads.", "Aucun contact correspondant."],
  restricted: [
    "Administrator access is required, or the service is unavailable.",
    "Un accès administrateur est requis, ou le service est indisponible.",
  ],
  cohort: ["Launch cohort", "Cohorte de lancement"],
  status: ["Review status", "Statut de suivi"],
  metrics: [
    "Measured events (consenting sessions only)",
    "Événements mesurés (sessions consentantes uniquement)",
  ],
  unknown: [
    "Invitations, account/seller activation, inventory and transactions are not instrumented here. Missing data is not zero.",
    "Les invitations, activations, inventaires et transactions ne sont pas mesurés ici. Une donnée absente ne signifie pas zéro.",
  ],
} as const;
export type CopyKey = keyof typeof copy;
export const options: Record<string, readonly [string, string, string][]> = {
  games: [
    ["pokemon", "Pokémon", "Pokémon"],
    ["magic", "Magic: The Gathering", "Magic: The Gathering"],
    ["yugioh", "Yu-Gi-Oh!", "Yu-Gi-Oh!"],
    ["one-piece", "One Piece", "One Piece"],
    ["riftbound", "Riftbound", "Riftbound"],
  ],
  province: [
    "AB",
    "BC",
    "MB",
    "NB",
    "NL",
    "NS",
    "NT",
    "NU",
    "ON",
    "PE",
    "QC",
    "SK",
    "YT",
  ].map((v) => {
    const names: Record<string, [string, string]> = {
      AB: ["Alberta", "Alberta"],
      BC: ["British Columbia", "Colombie-Britannique"],
      MB: ["Manitoba", "Manitoba"],
      NB: ["New Brunswick", "Nouveau-Brunswick"],
      NL: ["Newfoundland and Labrador", "Terre-Neuve-et-Labrador"],
      NS: ["Nova Scotia", "Nouvelle-Écosse"],
      NT: ["Northwest Territories", "Territoires du Nord-Ouest"],
      NU: ["Nunavut", "Nunavut"],
      ON: ["Ontario", "Ontario"],
      PE: ["Prince Edward Island", "Île-du-Prince-Édouard"],
      QC: ["Quebec", "Québec"],
      SK: ["Saskatchewan", "Saskatchewan"],
      YT: ["Yukon", "Yukon"],
    };
    return [v, names[v][0], names[v][1]];
  }),
  channels: [
    ["ebay", "eBay", "eBay"],
    ["shopify", "Shopify", "Shopify"],
    ["tcgplayer", "TCGplayer", "TCGplayer"],
    ["facebook", "Facebook", "Facebook"],
    ["lgs", "Local game store", "Boutique locale"],
    ["other", "Other", "Autre"],
  ],
  software: [
    ["sortswift", "SortSwift", "SortSwift"],
    ["carduploader", "CardUploader", "CardUploader"],
    ["binderpos", "BinderPOS", "BinderPOS"],
    ["spreadsheet", "Spreadsheet", "Tableur"],
    ["custom", "Custom tool", "Outil personnalisé"],
    ["none", "None", "Aucun"],
  ],
  frequency: [
    ["occasionally", "Occasionally", "À l’occasion"],
    ["monthly", "Monthly", "Chaque mois"],
    ["weekly", "Weekly", "Chaque semaine"],
  ],
  inventory: [
    ["under_1000", "Under 1,000 cards", "Moins de 1 000 cartes"],
    ["1000_9999", "1,000–9,999", "1 000–9 999"],
    ["10000_49999", "10,000–49,999", "10 000–49 999"],
    ["50000_plus", "50,000+", "50 000+"],
  ],
  sellerType: [
    ["individual", "Individual", "Particulier"],
    ["professional", "Professional", "Professionnel"],
    ["online_store", "Online store", "Boutique en ligne"],
    ["hobby_shop", "Hobby shop", "Boutique de loisirs"],
  ],
  experience: [
    ["starting", "Just starting", "Je débute"],
    ["under_1_year", "Under one year", "Moins d’un an"],
    ["1_3_years", "1–3 years", "1 à 3 ans"],
    ["3_plus_years", "3+ years", "Plus de 3 ans"],
  ],
  cohort: [
    ["unassigned", "Unassigned", "Non assignée"],
    ["internal", "Internal", "Interne"],
    ["founding_sellers", "Founding sellers", "Vendeurs fondateurs"],
    ["private_alpha", "Private alpha", "Alpha privée"],
    [
      "collector_closed_beta",
      "Collector closed beta",
      "Bêta privée collectionneurs",
    ],
    ["public", "Public", "Publique"],
  ],
  status: [
    ["new", "New", "Nouveau"],
    ["reviewing", "Reviewing", "En examen"],
    ["contacted", "Contacted", "Contacté"],
    ["waitlisted", "Waitlisted", "En attente"],
  ],
};
